USE cienciadelas;

CREATE TABLE IF NOT EXISTS cartas (
    id INT PRIMARY KEY,
    categoria VARCHAR(67) NOT NULL,
    personagem VARCHAR(100) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    custo DECIMAL(10,2) NOT NULL,
    efeito VARCHAR(255) NOT NULL,
    requisito VARCHAR(100) NOT NULL,
    sucesso VARCHAR(255) NOT NULL,
    falha VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO cartas
(id, categoria, personagem, nome, custo, efeito, requisito, sucesso, falha)
VALUES
(1, 'NORMAL', '—', 'Análise Genética', 0,
 'Aumenta Pesquisa em +1',
 '—',
 '—',
 '—'),

(2, 'NORMAL', '—', 'Sequenciamento Rápido', 1,
 'Aumenta Pesquisa em +2',
 '—',
 '—',
 '—'),

(3, 'NORMAL', '—', 'Resposta Epidemiológica', 2,
 'Aumenta Saúde em +3',
 '—',
 '—',
 '—'),

(4, 'NORMAL', '—', 'Monitoramento de Casos', 1,
 'Permite visualizar a próxima carta da Ameaça',
 '—',
 '—',
 '—'),

(5, 'NORMAL', '—', 'Distribuição de Insumos', 0,
 'Aumenta Infraestrutura em +1',
 '—',
 '—',
 '—'),

(6, 'NORMAL', '—', 'Coleta de Amostras', 1,
 'Aumenta Pesquisa em +1 e Saúde em +2',
 '—',
 '—',
 '—'),

(7, 'NORMAL', '—', 'Experimento Controlado', 0,
 'Aumenta Pesquisa em +1',
 '—',
 '—',
 '—'),

(8, 'NORMAL', '—', 'Ação em Campo', 2,
 'Aumenta Saúde, Pesquisa e Infraestrutura em +1',
 '—',
 '—',
 '—'),

(9, 'NORMAL', '—', 'Intervenção Emergencial', 2,
 'Aumenta Saúde em +2',
 '—',
 '—',
 '—'),

(10, 'NORMAL', '—', 'Desenvolvimento de Vacinas', 2,
 'Aumenta Pesquisa em +2 e Saúde em +1',
 '—',
 '—',
 '—'),

(11, 'ESPECIAL', 'Marie Curie', 'Radioatividade', 2,
 'Ameaça fica incapaz de aplicar efeitos por 2 turnos; Saúde -1',
 '—',
 '—',
 '—'),

(12, 'ESPECIAL', 'Marie Curie', 'Descoberta Científica', 3,
 'Próxima carta utilizada tem seus efeitos dobrados',
 '—',
 '—',
 '—'),

(13, 'ESPECIAL', 'Marie Curie', 'Energia Nuclear', 3,
 'Pesquisa +2 e Infraestrutura +1',
 '—',
 '—',
 '—'),

(14, 'ESPECIAL', 'Marie Curie', 'Experimento Avançado', 3,
 'Saúde +1, Pesquisa +1 e Infraestrutura +1 ao final de cada rodada durante 3 turnos',
 '—',
 '—',
 '—'),

(15, 'ESPECIAL', 'Marie Curie', 'Legado Científico', 3,
 'Pesquisa +1 no início de cada rodada durante 2 turnos',
 '—',
 '—',
 '—'),

(16, 'ESPECIAL', 'Jaqueline Goes de Jesus', 'Sequenciamento Genético', 3,
 'Anula os efeitos da Ameaça revelada durante esta rodada',
 '—',
 '—',
 '—'),

(17, 'ESPECIAL', 'Jaqueline Goes de Jesus', 'Diagnóstico Rápido', 3,
 'Permite utilizar 2 cartas adicionais na rodada, ignorando custos de Conhecimento',
 '—',
 '—',
 '—'),

(18, 'ESPECIAL', 'Jaqueline Goes de Jesus', 'Mapeamento Viral', 2,
 'Reduz em 1 todos os efeitos negativos aplicados aos recursos pelas Ameaças nesta rodada',
 '—',
 '—',
 '—'),

(19, 'ESPECIAL', 'Jaqueline Goes de Jesus', 'Resposta Imediata', 3,
 'Anula todos os efeitos negativos das Ameaças nesta rodada e recupera Saúde +1, Pesquisa +1 e Infraestrutura +1',
 '—',
 '—',
 '—'),

(20, 'ESPECIAL', 'Jaqueline Goes de Jesus', 'Controle Epidemiológico', 3,
 'Converte parcialmente efeitos negativos de uma Ameaça em benefícios',
 '—',
 '—',
 '—'),

(21, 'AMEAÇA', '—', 'Primeiros Casos do Surto', NULL,
 '—',
 'Pesquisa ≥ 7',
 'Saúde +2',
 'Saúde -2'),

(22, 'AMEAÇA', '—', 'Falha no Isolamento da Área Afetada', NULL,
 '—',
 'Infraestrutura ≥ 7',
 'Infraestrutura +1',
 'Infraestrutura -1'),

(23, 'AMEAÇA', '—', 'Origem Desconhecida do Vírus', NULL,
 '—',
 'Gastar 2 pontos de Pesquisa',
 'Pesquisa +1',
 'Saúde -1'),

(24, 'AMEAÇA', '—', 'Nova Variante Detectada', NULL,
 '—',
 'Pesquisa ≥ 7',
 'Saúde +1',
 'Infraestrutura -1'),

(25, 'AMEAÇA', '—', 'Superlotação dos Hospitais', NULL,
 '—',
 'Infraestrutura ≥ 9',
 'Saúde +1',
 'Saúde -1 e Infraestrutura -1'),

(26, 'AMEAÇA', '—', 'Contágio Fora de Controle', NULL,
 '—',
 'Saúde ≥ 10',
 'Pesquisa +1',
 'Saúde -1'),

(27, 'AMEAÇA', '—', 'Desinformação da População', NULL,
 '—',
 'Saúde ≥ 11 e Pesquisa ≥ 11',
 'Todos os recursos +1',
 'Saúde -1'),

(28, 'AMEAÇA', '—', 'Mutação Inesperada do Vírus', NULL,
 '—',
 'Gastar 8 pontos de Pesquisa',
 'Saúde +1',
 'Todos os recursos -1'),

(29, 'AMEAÇA', '—', 'Fracasso no Desenvolvimento da Vacina', NULL,
 '—',
 'Pesquisa ≥ 6',
 'Pesquisa +1',
 'Pesquisa -2'),

(30, 'AMEAÇA', '—', 'Risco nos Testes Clínicos', NULL,
 '—',
 'Pesquisa ≥ 7 e Infraestrutura ≥ 8',
 'Saúde +2',
 'Saúde -2'),

(31, 'AMEAÇA', '—', 'Colapso na Produção de Vacinas', NULL,
 '—',
 'Infraestrutura ≥ 10',
 'Infraestrutura +1',
 'Infraestrutura -2'),

(32, 'AMEAÇA', '—', 'Caos na Distribuição de Vacinas', NULL,
 '—',
 'Infraestrutura ≥ 12 e Saúde ≥ 12',
 'Saúde +2',
 'Saúde -1 e Infraestrutura -1'),

(33, 'AMEAÇA', '—', 'Crise Sanitária Internacional', NULL,
 '—',
 'Todos os recursos ≥ 14',
 'Todos os recursos +1',
 'Todos os recursos -2'),

(34, 'AMEAÇA', '—', 'Resistência à Imunização', NULL,
 '—',
 'Gastar 8 pontos de Pesquisa',
 'Saúde +2',
 'Saúde -2'),

(35, 'AMEAÇA', '—', 'Ameaça Global Iminente', NULL,
 '—',
 'Todos os recursos ≥ 16',
 'Vitória imediata',
 'Todos os recursos -3; se algum chegar a 0, derrota');